### ISSUE TITLE
Message service not working - throws error

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/match-a-pet#118]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Throws following error when in a new account, i go to messages tab, click on new message, type a message and click send
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/accounts/views.py", line 374, in SendDirect
    to_user = User.objects.get(username=to_user_username)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name

Exception Type: DoesNotExist at /send/
Exception Value: User matching query does not exist.
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

## Current Behavior

Throws error without informing the user if it's something wrong on his/her end or not.

## Ideas for Improvement

Have validations before sending a new message or if it's a backend error, look into the backend script.

## Steps to Reproduce

1. Register new account
2.activate account and log in
3.go to messages
4.click on new message, type a message and click send or press enter.

## Context (Environment)

Throws error instead of showing relevant error info to user unless it's an error from the development side.

Have validations before sending a new message or if it's a backend error, look into the backend script.

**Comment by benji7890** [comment]
fixed.
